# compose file for production
#
# docker-compose -p draw-prd -f docker-compose.yml up
#
# docker-compose -p draw-prd -f docker-compose.yml run web bin/rake assets:precompile --trace
#
# docker volume create --name=draw-prd-db-data
version: "3.7"

volumes:
  draw-prd-db-data:
    external: true
  # draw-redis-data:
  #   external: true
  # box: {} # used for the bundler, persistent store between runs

services:
  web:
    command: "/opt/draw/script/draw_start.sh"
    image: ghcr.io/balen/climate-data-rescue:production
    volumes:
      - /Users/balen/tmp/draw/assets:/opt/draw/public/assets
      - /Users/balen/tmp/draw/system:/opt/draw/public/system
      - /Users/balen/tmp/draw/packs:/opt/draw/public/packs
      # - /var/log/draw/web:/opt/draw/log
      # - /opt/draw/etc/draw:/config
      - type: tmpfs
        target: /app/tmp
    env_file:
      - .envrc
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - MYSQL_PASSWORD=H0rvendile
      - DB_HOST=draw-db
      - DEVISE_SECRET=aa77bb734faa9b935c1f8b68846e37aed9096cc9fb746copypastaf856594409a11b1086535e468edb2e5bbc18482b386b6264ada38703dcdefd94a291ab5a95eb5
      - SECRET_KEY_BASE=aa77bb734faa9b935c1f8b68846e37aed9096cc9fb746copypastaf856594409a11b1086535e468edb2e5bbc18482b386b6264ada38703dcdefd94a291ab5a95eb5
      - SECRET_TOKEN=aa77bb734faa9b935c1f8b68846e37aed9096cc9fb746copypastaf856594409a11b1086535e468edb2e5bbc18482b386b6264ada38703dcdefd94a291ab5a95eb5
    depends_on:
      - draw-db
      # - redis
    links:
      - draw-db
      # - redis
    ports:
      - "127.0.0.1:3000:3000"

  draw-db:
    container_name: draw-db
    image: mysql:5.7
    platform: linux/x86_64
    env_file:
      - .envrc
    volumes:
      - draw-prd-db-data:/var/lib/mysql
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  # redis:
  #   image: redis:alpine
  #   restart: always
  #   volumes:
  #     - draw-redis-data:/data
