default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db
  protocol: tcp
  port: 3306

development:
  <<: *default
  database: draw_dev

test:
  <<: *default
  database: draw_test


