# compose file for production
#
version: "3.7"

volumes:
  draw-redis-data:
    external: true

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - draw-redis-data:/data

  web:
    command: "/opt/draw/script/draw_start.sh"
    # TOOD
    # ghcr.io/OWNER/IMAGE_NAME:latest
    # image: 666959015006.dkr.ecr.us-west-2.amazonaws.com/draw:main
    volumes:
      - /opt/draw/shared/public/assets:/opt/draw/shared/public/assets
      - /opt/draw/shared/public/system:/opt/draw/shared/public/system
      - /var/log/draw/web:/opt/draw/log
      - /opt/draw/etc/draw:/config
      - type: tmpfs
        target: /app/tmp
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      # - PGID=1005
      # - PUID=1001
      # - DB_HOST=draw-db
    env_file:
      # - "/opt/chicago/etc/hostname.env"
      # - "/opt/chicago/etc/draw.env"
      # - "/opt/chicago/etc/draw-overrides.env"
      # - "/opt/chicago/etc/creds.env"
    depends_on:
      - redis
    links:
      - redis
    ports:
      - "127.0.0.1:3000:3000"
    restart: always

  # draw-sidekiq:
  #   command: "/opt/draw/script/draw.sh"
  #   image: 666959015006.dkr.ecr.us-west-2.amazonaws.com/draw:main
  #   volumes:
  #     - /var/log/draw/sidekiq:/opt/draw/log
  #     - type: tmpfs
  #       target: /app/tmp
  #     - /opt/chicago/etc/draw:/config
  #   environment:
  #     - PGID=1005
  #     - PUID=1001
  #     - RAILS_ENV=production
  #     - NODE_ENV=production
  #   env_file:
  #     - "/opt/chicago/etc/hostname.env"
  #     - "/opt/chicago/etc/draw.env"
  #     - "/opt/chicago/etc/draw-overrides.env"
  #     - "/opt/chicago/etc/creds.env"
  #   depends_on:
  #     - redis
  #   links:
  #     - redis
  #   restart: always
