# compose file for production
#
version: "3.7"

volumes:
  draw-redis-data:
    external: true
  draw-prd-db-data:
    external: true

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - draw-redis-data:/data

  draw-db:
    container_name: draw-db
    image: mysql:5.7
    platform: linux/x86_64
    env_file:
      - "/opt/draw/etc/hostname.env"
      - "/opt/draw/etc/draw.env"
    volumes:
      # - draw-prd-db-data:/var/lib/mysql
      - draw-prd-db-data:/opt/draw/lib/mysql
      - /opt/draw/etc/mysql/conf.d:/opt/draw/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always

  web:
    command: "/opt/draw/script/draw_start.sh"
    image: ghcr.io/balen/climate-data-rescue:production
    volumes:
      - /opt/draw/shared/public//assets:/opt/draw/public/assets
      - /opt/draw/shared/public/system:/opt/draw/public/system
      - /opt/draw/shared/public/packs:/opt/draw/public/packs
      - /opt/draw/etc/draw:/config
      - /var/log/draw/web:/opt/draw/log
      - type: tmpfs
        target: /app/tmp
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - DB_HOST=draw-db
      # - SIDEKIQ_REDIS_URL=redis://redis:6379/0
    env_file:
      - "/opt/draw/etc/hostname.env"
      - "/opt/draw/etc/draw.env"
    depends_on:
      - draw-db
      - redis
    links:
      - draw-db
      - redis
    ports:
      - "127.0.0.1:3000:3000"
    restart: always

  # draw-sidekiq:
  #   command: "/opt/draw/script/draw_sidekiq.sh"
  #   image: ghcr.io/balen/climate-data-rescue:production
  #   volumes:
  #     - /opt/draw/shared/public//assets:/opt/draw/public/assets
  #     - /opt/draw/shared/public/system:/opt/draw/public/system
  #     - /opt/draw/shared/public/packs:/opt/draw/public/packs
  #     - /opt/draw/etc/draw:/config
  #     - /var/log/draw/sidekiq:/opt/draw/log
  #     - type: tmpfs
  #       target: /app/tmp
  #   environment:
  #     - RAILS_ENV=production
  #     - NODE_ENV=production
  #     - DB_HOST=draw-db
  #   env_file:
  #     - "/opt/draw/etc/hostname.env"
  #     - "/opt/draw/etc/draw.env"
  #   depends_on:
  #     - draw-db
  #     - redis
  #   links:
  #     - draw-db
  #     - redis
  #   restart: always
